---
- name: Install Knative Eventing
  community.kubernetes.k8s:
    state: present
    definition: "{{ lookup('url', item, split_lines=False) }}"
  with_items:
    - "{{ knative_eventing_crds }}"
    - "{{ knative_eventing_core }}"
    - "{{ knative_eventing_channel }}"
    - "{{ knative_eventing_broker }}"    

- name: Add tag resolution disabled repositories
  community.kubernetes.k8s:
    kind: ConfigMap
    name: config-deployment
    namespace: knative-serving
    definition:
      apiVersion: v1
      kind: ConfigMap
      metadata:
        name: config-deployment
        namespace: knative-serving
      data:
        registriesSkippingTagResolving: kind.local,ko.local,dev.local    
