apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: metaflow-pipeline
rules:
  - apiGroups:
      - machinelearning.seldon.io
    resources:
      - seldondeployments
      - seldondeployments/status
    verbs:
      - "*"
  - apiGroups:
      - serving.kubeflow.org
    resources:
      - inferenceservices/status
    verbs:
      - get
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: metaflow-pipeline-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: metaflow-pipeline
subjects:
  - kind: ServiceAccount
    name: default
    namespace: metaflow
