---
- name: Install KFServing
  community.kubernetes.k8s:
    state: present
    definition: "{{ lookup('url', item, split_lines=False) }}"
  with_items:
    - "{{ kfserving_yaml }}"

- name: Update KfServing ConfigMap
  community.kubernetes.k8s:
    kind: ConfigMap
    name: inferenceservice-config
    namespace: kfserving-system
    definition:
      apiVersion: v1
      kind: ConfigMap
      metadata:
        name: inferenceservice-config
        namespace: kfserving-system
      data:
        ingress: |-
                {
                  "ingressGateway" : "knative-ingress-gateway.knative-serving",
                  "ingressService" : "istio-ingressgateway.istio-system.svc.cluster.local",
                  "localGateway" : "knative-local-gateway.knative-serving",
                  "localGatewayService" : "knative-local-gateway.istio-system.svc.cluster.local"
                }

- name: Wait for KFServing Controller Manager
  community.kubernetes.k8s_info:
    kind: Pod
    wait: yes
    label_selectors:
      - control-plane = kfserving-controller-manager
    namespace: kfserving-system
    wait_timeout: 600
  with_items:
    - kfserving-controller-manager
  when: kfserving_wait_for_deployments | bool
