---
- name: Create Namespaces
  include: namespaces.yaml

- name: Create Secrets
  include: secrets.yaml

- name: Git clone Seldon Core repo and checkout {{ seldon_core_version }}
  ansible.builtin.git:
    version: "{{ seldon_core_version }}"
    repo: "{{ seldon_core_repo }}"
    dest: "{{ inventory_dir }}/.resources/seldon-core"
  when: seldon_core_source_dir is undefined

- name: Set Seldon Core Directory
  set_fact: seldon_core_source_dir="{{ inventory_dir }}/.resources/seldon-core"
  when: seldon_core_source_dir is undefined

- name: Deploy Seldon Core
  community.kubernetes.helm:
    name: seldon-core
    release_namespace: "{{ seldon_system_namespace }}"
    chart_ref: "{{ seldon_core_source_dir }}/helm-charts/seldon-core-operator"
    values: "{{ core_values }}"
    values_files: "{{ core_values_files }}"
